server.port=8081
spring.application.name=auth-service



#H2 du lieu de so sanh login
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#H2 de xem database qua browser
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


